ecs_cluster_name = "leon-ecs-cluster-dev"
ecs_service_name = "leon-ecs-service-dev"
ecs_task_defn_family = "leon-ecs-task-def-dev"
ecs_container_name = "leon-container-dev"
ecs_port_name = "leon-3000-tcp-dev"
